### ISSUE TITLE
Container dies when being too specific with a provider

### ISSUE THREAD

**Issue by kashalls** [larivierec/cloudflare-ddns#322]
I copied the original config from mr. smurf, but ddns crashes out with:

`--zone-name ok8.sh --record-name ipv4.ok8.sh --provider icanhazip`

```
cloudflare-ddns
version: v1.0.1 (26d548e1b8e67fbd3975a84d812b0e0eb9c2bbfd)

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/larivierec/cloudflare-ddns/pkg/cmd.getProvider(...)
	/go/src/github.com/larivierec/cloudflare-ddns/pkg/cmd/ddns.go:301
github.com/larivierec/cloudflare-ddns/pkg/cmd.initialize()
	/go/src/github.com/larivierec/cloudflare-ddns/pkg/cmd/ddns.go:282 +0x2fa

```

[HelmRelease.yaml](https://github.com/kashalls/home-cluster/blob/main/kubernetes/main/apps/networking/cloudflare-ddns/app/helmrelease.yaml)

**Comment by larivierec** [comment]
Will take a look!
